appname: test
db:
  name:     test
  user:     postgres
  password: postgres
  host:     172.23.1.2
  port:     5432
  use:      true

contacts:
  - name:  jack
    email: jack@test.com
  - name:  tom
    email: tom@test.com

server:
  port: 8084
  host: localhost
  baseFilePath: C:/Users/dell/Desktop/tmp

imageExt: .jpg.jpeg.png.webp.gif