appname: test
db:
  name:     test
  user:     postgres
  password: postgres
  host:     172.23.1.2
  port:     5432
  use:      false

contacts:
  - name:  jack
    email: jack@test.com
  - name:  tom
    email: tom@test.com

server:
  port: 8084
  host: localhost
  baseFilePath: C:/Users/dell/Desktop/tmp

minio:
  endpoint: play.min.io
  id: Q3AM3UQ867SPQQA43P2F
  secret: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
  secure: true
  enable: true

imageExt: .jpg.jpeg.png.webp.gif